### PR TITLE
Rotate resized images based on EXIF data

### PR DESCRIPTION
**Pull request by wildlyinaccurate**
This PR augments/replaces the work done by @jameswood in #54. Changes

- Rename the option to `auto_rotate`
- Write tests to cover new functionality
- Minor version bump for new feature

### CODE REVIEW

**Comment by wildlyinaccurate** [comment]
@jameswood are you okay with the option being renamed to `auto_rotate`? I figure this is a little easier to understand than `respect_exif_rotation`?

**Comment by jameswood** [comment]
@wildlyinaccurate `auto_rotate` does it for me!

**Comment by jameswood** [comment]
I'm still getting used to this Git stuff, but it looks like the variable name might still need updating in `lib/jekyll-responsive-image/config.rb` - ?

**Comment by wildlyinaccurate** [comment]
Yep, good spot! I'll fix that up, then get this released so that you can use it. Thanks for all of your help!

**Comment by jameswood** [comment]
@wildlyinaccurate Nice one! I'm already using it... thanks to the lifehack of having stumbled across `/var/lib/gems/2.1.0/gems/jekyll-responsive-image-1.1.0/` and realising that I now have enough knowledge to be dangerous! Can't wait to do a genuine upgrade though ;)

**Pull request merged**
