### PR TITLE
Adds an ignored_extensions config option for animated gifs to not be altered

### PR DESCRIPTION
**Pull request by brandonb927**
I'm no ruby expert, so this is the best I can do 😅 ~I think there's tests for this project but I'm not confident making changes to them to support this configuration option.~ I've added a test for this configuration option as well. Let me know if this is something that could be included upstream, otherwise I'll just keep it in my fork.

### CODE REVIEW

**Comment by brandonb927** [comment]
@stalebot go away

**Comment by wildlyinaccurate** [comment]
Hey, sorry I didn't get a chance to look at this for a LONG time. I might be missing something here but isn't it possible for you to just not use the plugin for animated graphics? Or if the image path is dynamic, you could conditionally use the plugin, e.g.

```twig
{% unless path | split: "." | last == "gif" %}
    <img src="{{ path }}">
{% unless %}
```

**Comment by brandonb927** [comment]
> [...] isn't it possible for you to just not use the plugin for animated graphics? Or if the image path is dynamic, you could conditionally use the plugin [...]

I agree the solution I have proposed is not elegant _at all_, I just don't know of a better way to prevent `gif` files from even being processed at all; as far as I can tell, this is an all or nothing plugin.

My media files are all in a single folder and the plugin grabs everything in that folder, including `gif` files which may be multiple `Mb` in size and runs through the generation every time I need to regenerate my site. This can result in minutes of processing time before my site is built.

**Comment by wildlyinaccurate** [comment]
This plugin only processes files that are used in the `{% responsive_image %}` and `{% responsive_image_block %}` tags. So long as you don't pass your large GIFs into these tags, they won't be processed.

If you're experiencing long build times, you might want to try using `cache: true` in the plugin config. This prevents the same image from being processed more than once and can help on very large sites. (To clarify: images are only ever resized once, but the `cache` option skips the code that checks whether an image has already been resized)

**Comment by brandonb927** [comment]
Ehh I guess you're right, I'm trying to shoehorn a solution where I could just not use the plugin. My intention was to use the plugin to place the files in the directory they need to be in to serve so I didn't have to write it into my build steps.

I will close this PR as I can see there is no reason to include the code 😄

**Pull request closed without merging**
